master:
  image: jhazelwo/docksalt
  hostname: salt
  command: /root/init.sh
  container_name: salt_master
  volumes:
    - ./srv:/srv
minion:
  image: jhazelwo/docksalt
  hostname: minion
  command: /root/init.sh
# this container_name is ignored since master uses an explicit name already
# https://github.com/docker/compose/issues/2061
  container_name: salt_minion
  links:
    - master

