master:
  image: jhazelwo/docksalt
  hostname: salt
  command: /root/init.sh
  container_name: salt_master
  volumes:
    - ./srv:/srv/salt
minion:
  image: jhazelwo/docksalt
  links:
    - master
  hostname: minion
  command: /root/init.sh

